/**
 * Vendor the two webfonts into public/fonts so the PWA has zero third-party
 * origins at first paint and works fully offline.
 *
 * Google Fonts' css2 endpoint serves different faces per User-Agent; the modern
 * Chrome UA below gets woff2 (and a variable face for Sora's 400..700 range).
 * Only the `latin` subset is kept — the trip content is English.
 *
 * Re-run with: pnpm --filter @travel-companion/web fonts:vendor
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(appDir, "public/fonts");

const MODERN_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/** Sora carries the UI weights (400/600/650/700) as one variable face. */
const FAMILIES = [
  { slug: "sora", css: "family=Sora:wght@400..700" },
  { slug: "ibm-plex-mono", css: "family=IBM+Plex+Mono:wght@400;500" },
];

type Face = {
  family: string;
  style: string;
  weight: string;
  unicodeRange: string;
  url: string;
};

/** Split a css2 response into @font-face blocks tagged with their subset comment. */
function parseFaces(css: string): { subset: string; face: Face }[] {
  const out: { subset: string; face: Face }[] = [];
  const blocks = css.split("/*").slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf("*/")).trim();
    const pick = (key: string) =>
      block.match(new RegExp(`${key}:\\s*([^;]+);`))?.[1]?.trim() ?? "";
    const url = block.match(/url\((https:[^)]+)\)/)?.[1];
    if (!url) continue;
    out.push({
      subset,
      face: {
        family: pick("font-family").replace(/['"]/g, ""),
        style: pick("font-style"),
        weight: pick("font-weight"),
        unicodeRange: pick("unicode-range"),
        url,
      },
    });
  }
  return out;
}

async function get(url: string): Promise<Response> {
  const response = await fetch(url, { headers: { "User-Agent": MODERN_UA } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`);
  return response;
}

await mkdir(outDir, { recursive: true });
const rules: string[] = [
  "/* Generated by scripts/vendor-fonts.ts — do not edit by hand. */",
  "",
];

for (const family of FAMILIES) {
  const css = await (
    await get(`https://fonts.googleapis.com/css2?${family.css}&display=swap`)
  ).text();

  const latin = parseFaces(css).filter((entry) => entry.subset === "latin");
  if (latin.length === 0) throw new Error(`No latin subset found for ${family.slug}`);

  for (const [index, { face }] of latin.entries()) {
    const name =
      latin.length === 1 ? `${family.slug}-latin.woff2` : `${family.slug}-${face.weight}-latin.woff2`;
    const bytes = Buffer.from(await (await get(face.url)).arrayBuffer());
    await writeFile(resolve(outDir, name), bytes);
    console.log(`${name.padEnd(34)} ${(bytes.length / 1024).toFixed(1)} KB  weight ${face.weight}`);

    rules.push(
      "@font-face {",
      `  font-family: "${face.family}";`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      "  font-display: swap;",
      `  src: url("./fonts/${name}") format("woff2");`,
      `  unicode-range: ${face.unicodeRange};`,
      "}",
      "",
    );
    void index;
  }
}

await writeFile(resolve(appDir, "src/fonts.css"), rules.join("\n"), "utf8");
console.log(`\nWrote ${resolve(appDir, "src/fonts.css")}`);
